//
//  HomeViewController.swift
//  CleanSwiftTestProject
//
//  Created by Jovan on 4/13/19.
//  Copyright (c) 2019 Jovan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeDisplayLogic: DisplayLogic {
    // func displaySomething(_ viewModel: Home.Something.ViewModel)
    func displayChildNumber(_ viewModel: Home.GetChildNumber.ViewModel)
}

class HomeViewController: BaseViewController {

    // MARK: - Scene Component Properties
    var configurator: HomeConfigurator? {
        return baseConfigurator as? HomeConfigurator
    }
    var interactor: HomeBusinessLogic? {
        return baseInteractor as? HomeBusinessLogic
    }
    var router: HomeRouterInput? {
        return baseRouter as? HomeRouterInput
    }

    // MARK: Properties
    // var isSomething: Bool = true

    // Mark: - Outlets
    @IBOutlet var childNumberLabel: UILabel!

    // MARK: - Actions

    @IBAction func onGoToChildDidTouchUpInside(_ sender: Any) {
        router?.showNewScreen()
    }

    // MARK: - Object Lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        baseConfigurator = HomeConfigurator()
        configurator?.configure(self)
    }
    
    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
}

extension HomeViewController: HomeDisplayLogic {

    // MARK: - Display Logic

    func displayChildNumber(_ viewModel: Home.GetChildNumber.ViewModel) {
        childNumberLabel.text = viewModel.number
    }

    // MARK: - Utility Methods

}
