//
//  HomeInteractor.swift
//  CleanSwiftTestProject
//
//  Created by Jovan on 4/13/19.
//  Copyright (c) 2019 Jovan. All rights reserved.
//
//  This file was 'partially' generated by the Clean Swift templates created by Jovan Radivojsa (a.k.a. joxoleon),
//  Based on the original clean swift templates created by Raymond Law: http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic: BusinessLogic {
    // func doSomething(_ request: Home.Something.Request)
}

protocol HomeDataStore: DataStore {
    // var name: String { get set }
}

class HomeInteractor: BaseInteractor, HomeBusinessLogic, HomeDataStore {

    // MARK: - Scene Component Properties
    var presenter: HomePresentationLogic? {
        return basePresenter as? HomePresentationLogic
    }
    var worker: HomeWorker? {
        return baseWorker as? HomeWorker
    }

    // MARK: - Properties
    // var name: String

    // MARK: - Receive data from child scene

    override func onBaseChildViewControllerClosing(childDataStore: DataStore) {
        // Receive data from child data store
        if let childData = childDataStore as? ChildDataStore, let childNumber = childData.childNumber {

            presenter?.presentChildNumber(Home.GetChildNumber.Response(number: childNumber))
        }
    }

    // MARK: - Business Logic

    // func doSomething(_ request: Home.Something.Request) {
    //     worker.doSomeWork()
    //     presenter?.presentSomething(TestScene.Something.Response())
    // }

    // MARK: - Utility Methods

    // func isSomethingSomething() -> Bool { return true }
}
