//
//  HomeRouter.swift
//  CleanSwiftTestProject
//
//  Created by Jovan on 4/13/19.
//  Copyright (c) 2019 Jovan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeRoutingNavigation: RoutingNavigation {
    func showNewScreen()
}

protocol HomeDataPassing: DataPassing {
}

typealias HomeRouterInput = HomeRoutingNavigation & HomeDataPassing

class HomeRouter: BaseRouter, HomeRouterInput {
    
    private struct Segues {
        static let ShowNextScreenIdentifier = "showChild"
    }

    // MARK: - Scene Components
    var dataStore: HomeDataStore? {
        return baseDataStore as? HomeDataStore
    }
    weak var viewController: HomeViewController? {
        return baseViewController as? HomeViewController
    }

    // MARK: - Properties
    // var isSomething: Bool = true

    // MARK: Navigation
    
    func showNewScreen() {
        performSegueWithIdentifier(segueId: Segues.ShowNextScreenIdentifier)
    }
    
    // MARK: Passing data
    
    override func passDataToNextScene(segue: UIStoryboardSegue) {
        super.passDataToNextScene(segue: segue)
        if segue.identifier == Segues.ShowNextScreenIdentifier {
            // Pass Relevant Data
        }
    }
}
