//
//  HomeModels.swift
//  CleanSwiftTestProject
//
//  Created by Jovan on 4/13/19.
//  Copyright (c) 2019 Jovan. All rights reserved.
//
//  This file was 'partially' generated by the Clean Swift templates created by Jovan Radivojsa (a.k.a. joxoleon),
//  Based on the original clean swift templates created by Raymond Law: http://clean-swift.com
//

import UIKit

struct Home: Models {

    // MARK: - Data definitions

    // MARK: - Use cases
    struct GetChildNumber {
        struct Response {
            let number: String
        }
        typealias ViewModel = Response
    }
}
