//
//  EmailValidationModels.swift
//  CleanSwiftTestProject
//
//  Created by Jovan on 4/14/19.
//  Copyright (c) 2019 Jovan. All rights reserved.
//
//  This file was 'partially' generated by the 'Component Based Clean Swift Templates' created by Jovan Radivojsa (a.k.a. joxoleon),
//  Based on the clean swift templates created by Raymond Law: http://clean-swift.com
//

import UIKit

struct EmailValidation: Models {

    // MARK: - Data definitions

    // MARK: - Use cases

    // struct Something {
    //     struct Request {
    //     }
    //     struct Response {
    //     }
    //     struct ViewModel {
    //     }
    // }
}
