//
//  BaseViewController.swift
//  CleanSwiftTestProject
//
//  Created by Jovan on 4/13/19.
//  Copyright (c) 2019 Jovan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class BaseViewController: UIViewController, DisplayLogic, CleanViewController {

    // MARK: - Scene Component Properties
    var configurator: ConfiguratorLogic?
    var interactor: BusinessLogic?
    var router: RouterInput?

    // MARK: - Object Lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        configurator = BaseConfigurator()
        configurator?.configure(self)
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Perform initialization of the scene
        // interactor?.doSomething()
    }

    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        if self.isMovingFromParent {
            router?.passDataToPreviousScene()
        }
    }

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router?.passDataToNextScene(segue: segue)
    }
}
