//
//  ChildRouter.swift
//  CleanSwiftTestProject
//
//  Created by Jovan on 4/13/19.
//  Copyright (c) 2019 Jovan. All rights reserved.
//
//  This file was 'partially' generated by the 'Component Based Clean Swift Templates' created by Jovan Radivojsa (a.k.a. joxoleon)
//  Based on the clean swift templates created by Raymond Law: http://clean-swift.com
//

import UIKit

protocol ChildRoutingNavigation: RoutingNavigation {
    func showNewScreen()
}

protocol ChildDataPassing: DataPassing {}

typealias ChildRouterInput = ChildRoutingNavigation & ChildDataPassing

class ChildRouter: BaseRouter, ChildRouterInput {
    
    private struct Segues {
        static let ShowNextScreenIdentifier = ""
    }

    // MARK: - Scene Components
    var dataStore: ChildDataStore? {
        return baseDataStore as? ChildDataStore
    }
    weak var viewController: ChildViewController? {
        return baseViewController as? ChildViewController
    }

    // MARK: - Properties
    // var isSomething: Bool = true

    // MARK: Navigation

    func showNewScreen() {
        performSegueWithIdentifier(segueId: Segues.ShowNextScreenIdentifier)
    }

    // MARK: Passing data

    override func passDataToNextScene(segue: UIStoryboardSegue) {
        if segue.identifier == Segues.ShowNextScreenIdentifier {
            // Pass Relevant Data
        }
    }
}
