//
//  ChildPresenter.swift
//  CleanSwiftTestProject
//
//  Created by Jovan on 4/13/19.
//  Copyright (c) 2019 Jovan. All rights reserved.
//
//  This file was 'partially' generated by the 'Component Based Clean Swift Templates' created by Jovan Radivojsa (a.k.a. joxoleon),
//  Based on the clean swift templates created by Raymond Law: http://clean-swift.com
//

import UIKit

protocol ChildPresentationLogic: PresentationLogic {
}

class ChildPresenter: BasePresenter, ChildPresentationLogic {

    struct Constants {
        // static let UserNameTextColor = UIColor.black
    }

    // MARK: - Scene Component Properties
    weak var viewController: ChildDisplayLogic? {
        return baseViewController as? ChildDisplayLogic
    }

    // MARK: - Properties
    // var isSomething: Bool = true

    // MARK: - Presentation logic

    // func presentSomething(_ response: Child.Something.Response) {
    //     viewController?.displaySomething(Child.Something.ViewModel())
    // }

    // MARK: - Utility

}
